# eureka.client.registerWithEureka ：表示是否将自己注册到Eureka Server，默认为true。由于当前这个应用就是Eureka Server，故而设为false
# eureka.client.fetchRegistry ：表示是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设为false。
# eureka.client.serviceUrl.defaultZone ：设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
#// Eureka Server注册服务的地址
#server:
#  port: 8888
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#  server:
##    enable-self-preservation: false
#
#spring:
#  application:
#    name: eureka
#
#security:
#  basic:
#    enabled: true
#  user:
#    name: kane
#    password: 123456
#security:
#  basic:
#    enabled: false
#  user:
#    name: user
#    password: passwd123
#
#server:
#  port: 8761
#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
##    serviceUrl:
##      defaultZone: http://user:passwd123@localhost:${server.port}/eureka/
#management:
#  security:
#    enabled: false
#https://github.com/spring-cloud/spring-cloud-netflix/issues/622

security:
  basic:
    enabled: false
  user:
      name: user
      password: password
  enable-csrf: false
server:
  port: 16801

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://localhost:18802/eureka/
#      defaultZone: http://user:password@localhost:${server.port}/eureka/

